### ISSUE TITLE
request: history of recently audible tabs

### ISSUE THREAD

**Issue by nemothorx** [8084/switch-to-audible-tab#1]
Some tabs are only audible for only a fraction of a second - alert beeps. Finding these after the audio has finished would be a considerable feature improvement. Perhaps as an option to keep tabs in the "audible tab" list for X seconds after audio finishes? Or a menu with categories like "tabs audible now | tabs audible recently"? TBH, the feature is the important idea here, not the UI! :) 

Is it possible?

**Comment by klntsky** [comment]
That's a nice feature to have, indeed.

I've already considered possible ways to implement it, and AFAIK there's no better way than [querying](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query) for audible tabs every fraction of second, hoping that the gap between queries will be tiny enough to overlap with the sound.

That's a performance hell, though.

I think I could add it, but leave disabled by default.

**Comment by nemothorx** [comment]
ooh, that does sound like it could be quite awkward, though I'd be willing to give it a go and see if the performance hit is worth the function (esp if the query interval is adjustable?)

But even if nothing else comes of this, thankyou for the consideration! :)

**Comment by nemothorx** [comment]
I asked a friend who follows firefox dev (but afaik doesn't write addons), and he pointed this out: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated

It seemed to us that a listener could be added that only cares about the audible property - and so firefox would provide notification about audible status changes on tabs without needing to poll. 

Do you think we're reading that right?

**Comment by klntsky** [comment]
Great, thank you! Somehow I missed this API. This, basically, solves everything.

**Comment by klntsky** [comment]
I'm on it.

I have two strategies for notifications in mind:

- if there's a notification, mark tab as audible permanently
- if there's a notification, allow jumping to it once, but then forget about it until the next notification

What do you think should be the default?

**Comment by nemothorx** [comment]
My imagined preference is a menu (in the context menu?) showing recently audible tabs. Keep the keybinding and default button behaviour unchanged (I note here that I always use the button since alt+shift+a is trapped by another addon)

Context menu would let me see what was recently active and make a decision about switching to that tab or not (based on the tab and how long ago it had active audio - if that information was presented in the menu also)

Of the options you present, I think the second makes most sense  :)

**Comment by klntsky** [comment]
> I note here that I always use the button since alt+shift+a is trapped by another addon

I guess I could also make it configurable later.

> Context menu would let me see what was recently active and make a decision about switching to that tab or not (based on the tab and how long ago it had active audio - if that information was presented in the menu also)

That's not the kind of behavior I had in mind, but OK.

> Of the options you present, I think the second makes most sense :)

Agreed.

**Comment by nemothorx** [comment]
My thinking for a menu is that "what made noise recently" could easily be multiple things (eg: I have facebook, slack, google and discord - and possibly other I don't remember) all sending momentary alert messages. So I'd value being able to identify what my options are before choosing between - and I imagine (ahead of time) that it would be relatively common for me. 

The current behaviour is much more tuned (for my usage at least!) to "halp, I lost my youtube tab" style of finding that one tab that is audible - choice has been irrelevant!

**Comment by klntsky** [comment]
@nemothorx 

> I note here that I always use the button since alt+shift+a is trapped by another addon

The hotkey can be configured, see https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by klntsky** [comment]
@nemothorx notification following feature has been implemented. 

I made it not in a way you requested.

> So I'd value being able to identify what my options are before choosing between

The disadvantage is that to do that you need an interface. Interfaces scare people, especially when the goal is performing such a simple task. Clicking the icon once more is intuitive, but selecting from a menu requires some context switching.

In real life scenarios for most people number of clicks will rarely exceed one, because by default notifications are prioritized over normal audible tabs.

**Comment by nemothorx** [comment]
Looks good. In an ideal world I'd like to get a list of all recent notifications tabs, but in practice, I probably rarely need it, and your solution that categorises audio into normal and notifications, and prioritises the notifications first... seems to me a very elegant solution overall. Thankyou! :) 

[ps: the other new options - to mark certain domains as audible by default and switch to them when no "actual" audio tabs... that might soon become my new favourite thing. fantastic idea :) ]
